# Basic
title: Matcha00
subtitle: 努力努力努力
welcome_message: <a href="#" target="_blank">我是陈欢</a>
description: iOS Android 前端 Python
creator: <a href="http://matcha00.me">@Matcha00</a>


permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 了解更多关于我, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Matcha000000
    github: Matcha00
    twitter: themeow00
    mail: chmatcha00@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
